### ISSUE TITLE
[Bug] Stick crafting recipes only work in upper left corner of crafting grid

### ISSUE THREAD

**Issue by DWX12** [Arcadiax/BonsaiTrees#2]
Trying out this cool little mod and noticed that the recipes for sticks only work if the sticks are in the upper left corner of a 3x3 crafting grid. I would like to see the recipe work in all possible configurations of the 2x2 pattern.

Thanks.

**Comment by Arcadiax** [comment]
I'll have a look in to this, thanks for logging an issue!
