### ISSUE TITLE
[Bug] Mod ID conflict with the Bonsai Trees mod

### ISSUE THREAD

**Issue by DWX12** [Arcadiax/BonsaiTrees#3]
When trying to use this mod along side the Bonsai Trees mod I get a mod id conflict.
https://minecraft.curseforge.com/projects/bonsai-trees

I have opened an issue on their side too that hopefully someone can fix.
https://github.com/thraaawn/BonsaiTrees/issues/101

Thank you.

**Comment by Arcadiax** [comment]
Hey I'm really sorry I missed this, I didn't get a notification.
The other mod is much larger than mine so I wouldn't expect them to change, I'll try and get a new version pushed with a new modid, if you're still interested :)

**Comment by Arcadiax** [comment]
Fixed in 52fe0ff034db48e169f113a916c811a188ab28a1
Will be in the next build on curseforge
